# Generated by Django 6.0.3 on 2026-06-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=60)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('species', models.CharField(max_length=40)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Pregnant', 'Pregnant'), ('Quarantine', 'Quarantine'), ('Sold', 'Sold'), ('Deceased', 'Deceased')], default='Healthy', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('origin', models.CharField(choices=[('Born in herd', 'Born in herd'), ('Purchased', 'Purchased')], default='Born in herd', max_length=30)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farms.farm')),
            ],
            options={
                'ordering': ['tag_id'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('body_condition', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='livestock.animal')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Observation', 'Observation'), ('Treatment', 'Treatment'), ('Injury', 'Injury'), ('Illness', 'Illness'), ('Recovery', 'Recovery'), ('Other', 'Other')], default='Observation', max_length=30)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=240)),
                ('treatment', models.CharField(blank=True, max_length=240)),
                ('vet_name', models.CharField(blank=True, max_length=120)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='livestock.animal')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=160)),
                ('date_given', models.DateField()),
                ('next_due', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=120)),
                ('batch_no', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='livestock.animal')),
            ],
            options={
                'ordering': ['-date_given', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('farm', 'tag_id'), name='unique_tag_per_farm'),
        ),
    ]
