# Generated by Django 6.0.3 on 2026-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
