# Generated by Django 6.0.3 on 2026-06-28 13:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_zero_born_purchase_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='animal',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12),
        ),
    ]
