# Generated by Django 6.0.3 on 2026-07-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('finances', '0002_expense_description_sale_description_sale_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('partner_type', models.CharField(choices=[('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Both', 'Both')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_partners', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('Supply to farm', 'Supply to farm'), ('Farm output', 'Farm output')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('goods_or_services', models.CharField(max_length=240)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('On delivery', 'On delivery'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Seasonal', 'Seasonal'), ('Other', 'Other')], default='Monthly', max_length=30)),
                ('agreed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Paused', 'Paused'), ('Ended', 'Ended')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='farms.farm')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='finances.tradingpartner')),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('Payable', 'Payable'), ('Receivable', 'Receivable')], max_length=20)),
                ('invoice_number', models.CharField(max_length=80)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=240)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Part paid', 'Part paid'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Issued', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finances.farmcontract')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='farms.farm')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finances.tradingpartner')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('farm', 'invoice_number'), name='unique_invoice_number_per_farm')],
            },
        ),
    ]
