# Generated by Django 6.0.3 on 2026-07-04 08:23

import django.db.models.deletion
from django.db import migrations, models


def backfill_invoice_items(apps, schema_editor):
    Invoice = apps.get_model("finances", "Invoice")
    InvoiceItem = apps.get_model("finances", "InvoiceItem")
    for invoice in Invoice.objects.all():
        InvoiceItem.objects.create(
            invoice=invoice,
            description=invoice.description or invoice.invoice_number,
            quantity=1,
            unit="",
            unit_price=invoice.amount,
            line_total=invoice.amount,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_tradingpartner_farmcontract_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(backfill_invoice_items, migrations.RunPython.noop),
    ]
