# Generated by Django 6.0.3 on 2026-07-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('finances', '0004_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=180)),
                ('purpose', models.CharField(max_length=240)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Seasonal', 'Seasonal'), ('Flexible', 'Flexible')], default='Monthly', max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paid', 'Paid'), ('Defaulted', 'Defaulted'), ('Written off', 'Written off')], default='Active', max_length=20)),
                ('collateral', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='farms.farm')),
            ],
            options={
                'ordering': ['status', 'due_date', '-issue_date', 'lender'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(blank=True, max_length=80)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finances.loan')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
