import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const COLORS = {
  green: [47, 69, 56],
  rust: [162, 59, 46],
  gold: [217, 164, 65],
  ink: [42, 36, 25],
  muted: [110, 100, 82],
  line: [228, 220, 200],
  cream: [250, 246, 236],
};

const money = value => `KES ${(Number(value) || 0).toLocaleString("en-KE", {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
})}`;

const dateLabel = value => {
  if (!value) return "-";
  const date = new Date(`${value}T00:00:00`);
  return Number.isNaN(date.getTime()) ? "-" : date.toLocaleDateString("en-GB", {
    day: "2-digit", month: "short", year: "numeric",
  });
};

const safeName = value => String(value || "document")
  .trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

function createDocument({ farm, title, number, status, date }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  doc.setProperties({
    title: `${title} ${number}`,
    subject: `${title} generated by Farm Ledger`,
    author: farm?.name || "Farm Ledger",
    creator: "Farm Ledger",
  });
  doc.setFillColor(...COLORS.green);
  doc.rect(0, 0, 210, 42, "F");
  doc.setFillColor(...COLORS.gold);
  doc.roundedRect(16, 12, 12, 12, 2, 2, "F");
  doc.setTextColor(...COLORS.green);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("FL", 22, 20.5, { align: "center" });
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text(farm?.name || "Farm Ledger", 34, 17);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(205, 215, 207);
  doc.text(farm?.location || "Farm management workspace", 34, 23);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(19);
  doc.setTextColor(255, 255, 255);
  doc.text(title.toUpperCase(), 194, 17, { align: "right" });
  doc.setFontSize(9);
  doc.setTextColor(225, 231, 226);
  doc.text(number, 194, 23, { align: "right" });

  doc.setTextColor(...COLORS.muted);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("DOCUMENT DATE", 16, 53);
  doc.text("STATUS", 79, 53);
  doc.text("GENERATED", 142, 53);
  doc.setTextColor(...COLORS.ink);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(dateLabel(date), 16, 59);
  doc.text(status || "Recorded", 79, 59);
  doc.text(new Date().toLocaleDateString("en-GB"), 142, 59);
  doc.setDrawColor(...COLORS.line);
  doc.line(16, 65, 194, 65);
  return doc;
}

function addDetails(doc, entries, startY = 73) {
  const width = 178 / Math.min(entries.length, 3);
  entries.forEach((entry, index) => {
    const x = 16 + (index % 3) * width;
    const row = Math.floor(index / 3);
    const y = startY + row * 18;
    doc.setTextColor(...COLORS.muted);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(String(entry.label).toUpperCase(), x, y);
    doc.setTextColor(...COLORS.ink);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(String(entry.value || "-"), width - 5);
    doc.text(lines.slice(0, 2), x, y + 6);
  });
  return startY + Math.ceil(entries.length / 3) * 18;
}

function addTotal(doc, label, value, y, accent = COLORS.green) {
  doc.setFillColor(...COLORS.cream);
  doc.roundedRect(118, y, 76, 18, 2, 2, "F");
  doc.setTextColor(...COLORS.muted);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(label.toUpperCase(), 124, y + 7);
  doc.setTextColor(...accent);
  doc.setFontSize(14);
  doc.text(money(value), 188, y + 12, { align: "right" });
}

function addNotes(doc, notes, y) {
  if (!notes) return;
  doc.setTextColor(...COLORS.muted);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("NOTES", 16, y);
  doc.setTextColor(...COLORS.ink);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(doc.splitTextToSize(String(notes), 178), 16, y + 6);
}

function addFooter(doc) {
  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(...COLORS.line);
    doc.line(16, 281, 194, 281);
    doc.setTextColor(...COLORS.muted);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.text("Computer-generated document from Farm Ledger. No signature is required.", 16, 287);
    doc.text(`Page ${page} of ${pages}`, 194, 287, { align: "right" });
  }
}

export function buildInvoicePdf(invoice, farm) {
  const doc = createDocument({
    farm, title: "Invoice", number: invoice.invoiceNumber,
    status: invoice.status, date: invoice.issueDate,
  });
  const detailEnd = addDetails(doc, [
    { label: invoice.direction === "Receivable" ? "Bill to" : "Supplier", value: invoice.partnerName },
    { label: "Due date", value: dateLabel(invoice.dueDate) },
    { label: "Contract", value: invoice.contractTitle || "No linked contract" },
  ]);
  doc.setTextColor(...COLORS.ink);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(invoice.description || "Invoice items", 16, detailEnd + 2);
  autoTable(doc, {
    startY: detailEnd + 8,
    head: [["Description", "Qty", "Unit", "Unit price", "Amount"]],
    body: (invoice.items || []).map(item => [
      item.description,
      String(item.quantity ?? 0),
      item.unit || "-",
      money(item.unitPrice),
      money(item.lineTotal ?? Number(item.quantity || 0) * Number(item.unitPrice || 0)),
    ]),
    theme: "plain",
    margin: { left: 16, right: 16, bottom: 22 },
    styles: { font: "helvetica", fontSize: 9, cellPadding: 3, textColor: COLORS.ink },
    headStyles: { fillColor: COLORS.green, textColor: [255, 255, 255], fontStyle: "bold" },
    columnStyles: { 1: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right", fontStyle: "bold" } },
    alternateRowStyles: { fillColor: COLORS.cream },
  });
  const tableEnd = doc.lastAutoTable.finalY + 7;
  addTotal(doc, "Invoice total", invoice.amount, tableEnd);
  addDetails(doc, [
    { label: "Amount paid", value: money(invoice.amountPaid) },
    { label: "Balance due", value: money(Math.max(Number(invoice.amount)-Number(invoice.amountPaid),0)) },
  ], tableEnd + 25);
  addNotes(doc, invoice.notes, tableEnd + 48);
  addFooter(doc);
  return doc;
}

function buildReceipt(record, farm, kind) {
  const isSale = kind === "Sale";
  const number = `${isSale ? "SALE" : "EXP"}-${String(record.id).padStart(6, "0")}`;
  const doc = createDocument({ farm, title: `${kind} Receipt`, number, status: "Recorded", date: record.date });
  const details = isSale ? [
    { label: "Received from", value: record.buyer || "Walk-in customer" },
    { label: "Sale type", value: record.type },
    { label: "Animal", value: record.animalLabel || "Not linked" },
  ] : [
    { label: "Paid to", value: record.vendor || "Not specified" },
    { label: "Expense category", value: record.category },
    { label: "Record source", value: record.autoLogged ? "Auto-logged" : "Manual" },
  ];
  const y = addDetails(doc, details);
  doc.setFillColor(...COLORS.cream);
  doc.roundedRect(16, y + 2, 178, 38, 2, 2, "F");
  doc.setTextColor(...COLORS.muted);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("DESCRIPTION", 22, y + 11);
  doc.setTextColor(...COLORS.ink);
  doc.setFontSize(11);
  doc.text(doc.splitTextToSize(record.description || "-", 164).slice(0, 2), 22, y + 19);
  if (isSale && record.quantity) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`Quantity: ${record.quantity}   Unit price: ${money(record.unitPrice)}`, 22, y + 32);
  }
  addTotal(doc, isSale ? "Amount received" : "Amount paid", record.amount, y + 49, isSale ? COLORS.green : COLORS.rust);
  addNotes(doc, record.notes, y + 76);
  addFooter(doc);
  return { doc, number };
}

export function downloadInvoicePdf(invoice, farm) {
  buildInvoicePdf(invoice, farm).save(`invoice-${safeName(invoice.invoiceNumber)}.pdf`);
}

export function downloadSaleReceiptPdf(sale, farm) {
  const { doc, number } = buildReceipt(sale, farm, "Sale");
  doc.save(`${safeName(number)}.pdf`);
}

export function downloadExpenseReceiptPdf(expense, farm) {
  const { doc, number } = buildReceipt(expense, farm, "Expense");
  doc.save(`${safeName(number)}.pdf`);
}

export const buildSaleReceiptPdf = (sale, farm) => buildReceipt(sale, farm, "Sale").doc;
export const buildExpenseReceiptPdf = (expense, farm) => buildReceipt(expense, farm, "Expense").doc;
