# Generated by Django 6.0.3 on 2026-07-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='subscription_billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='subscription_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('business', 'Business'), ('commercial', 'Commercial'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='subscription_started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='subscription_status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
